/**
 * Created by jared on 3/21/16.
 */

var CountryHash = {
    'alabama': "united states",
    'al': "united states",
    'alaska': "united states",
    'ak': "united states",
    'arizona': "united states",
    'az': "united states",
    'arkansas': "united states",
    'ar': "united states",
    'california': "united states",
    'ca': "united states",
    'colorado': "united states",
    'co': "united states",
    'connecticut': "united states",
    'conn': "united states",
    'ct': "united states",
    'delaware': "united states",
    'de': "united states",
    'florida': "united states",
    'fl': "united states",
    'georgia': "united states",
    'ga': "united states",
    'hawaii': "united states",
    'hi': "united states",
    'idaho': "united states",
    'id': "united states",
    'illinois': "united states",
    'il': "united states",
    'indiana': "united states",
    'in': "united states",
    'iowa': "united states",
    'ia': "united states",
    'kansas': "united states",
    'ks': "united states",
    'kentucky': "united states",
    'ky': "united states",
    'louisiana': "united states",
    'la': "united states",
    'maine': "united states",
    'me': "united states",
    'maryland': "united states",
    'md': "united states",
    'massachusetts': "united states",
    'ma': "united states",
    'mass': "united states",
    'michigan': "united states",
    'mi': "united states",
    'minnesota': "united states",
    'mn': "united states",
    'mississippi': "united states",
    'ms': "united states",
    'missouri': "united states",
    'mo': "united states",
    'montana': "united states",
    'mo': "united states",
    'nebraska': "united states",
    'ne': "united states",
    'nevada': "united states",
    'nv': "united states",
    'new hampshire': "united states",
    'nh': "united states",
    'new jersey': "united states",
    'nj': "united states",
    'new mexico': "united states",
    'nm': "united states",
    'new york': "united states",
    'ny': "united states",
    'north carolina': "united states",
    'nc': "united states",
    'north dakota': "united states",
    'nd': "united states",
    'ohio': "united states",
    'oh': "united states",
    'oklahoma': "united states",
    'ok': "united states",
    'oregon': "united states",
    'or': "united states",
    'pennsylvania': "united states",
    'pa': "united states",
    'rhode island': "united states",
    'ri': "united states",
    'south carolina': "united states",
    'sc': "united states",
    'south dakota': "united states",
    'sd': "united states",
    'tennessee': "united states",
    'tn': "united states",
    'texas': "united states",
    'tx': "united states",
    'utah': "united states",
    'ut': "united states",
    'vermont': "united states",
    'vt': "united states",
    'virginia': "united states",
    'va': "united states",
    'washington': "united states",
    'wa': "united states",
    'west virginia': "united states",
    'wv': "united states",
    'wisconsin': "united states",
    'wi': "united states",
    'wyoming': "united states",
    'wy': "united states",
    'usa': "united states",
    'united kingdom': "england",
    'uk': "england",
    'england uk': "england",
    'eng': "england",
    'engl': "england",
    'scot': "scotland",
    'schotland': "scotland",
    'scottland': "scotland",
    'danmark': "denmark",
    'dnmk' : "denmark",
    'dnmark': "denmark",
    'den': "denmark",
    'nederland': "netherlands",
    'wls': "wales",
    'switz': "switzerland",
    'swtz': "switzerland",
    'swdn': "sweden",
    'sxny': "saxony",
    'sax': "saxony",


    'british america': "united states",
    'british colonial america' : "united states",
    'colonial america': 'united states',
    'colonial british america': 'united states',
    'colonies': 'united states',
    'American Colonies': 'united states',
    'ocean / off coast of north carolina ?' : "oceans",
    '?' : "unknown",
    'united states' : "united states",
    'united states of america': "united states",
    'norway' : "norway",
    'of scotland': "scotland",
    'sscotland': "scotland",
    'neth': "netherlands",
    'channisles': 'channel islands',
    'ch is': 'channel islands',
    'ci': 'channel islands',
    'c i': 'channel islands',
    'ch': 'channel islands',
    'cis': 'channel islands',
    'channel isles': 'channel islands',
    'chann isles': 'channel islands',
    'chan islands': 'channel islands',

    'gt br': 'great britain',
    'g b': 'great britain'

};